// Full EN / BN dictionary for every screen, public + admin.
export const dict = {
  en: {
    brand: { name: 'Cumilla Resort', full: 'Cumilla Resort', place: 'Kotbari, Cumilla, Bangladesh' },
    nav: {
      home: 'Home', villas: 'Villas', experiences: 'Experiences', dining: 'Dining',
      gallery: 'Gallery', about: 'About', offers: 'Offers',
      contact: 'Contact', bookNow: 'Book Now', management: 'Management',
      availability: 'Live Availability', events: 'Events & Weddings',
      explore: 'Around Us', faq: 'FAQ', myBooking: 'My Booking', features: 'Features',
    },
    events: {
      pageTitle: 'Events & Weddings', pageSub: 'Tea-garden ceremonies, forest retreats and milestone days — planned end to end.',
      includes: 'Included', from: 'From',
      inqTitle: 'Plan Your Event', inqHint: 'Tell us the occasion — our events team replies within a day.',
      name: 'Your Name', phone: 'Phone', date: 'Preferred Date', type: 'Event Type',
      types: ['Wedding', 'Corporate Retreat', 'Birthday / Milestone', 'Other'],
      msg: 'Tell us more', send: 'Send Inquiry',
      sent: 'Thank you! Our events team will call you within 24 hours. (Demo)',
    },
    explore: {
      pageTitle: 'Around Cumilla', pageSub: 'The best of Cumilla within a morning’s reach — we arrange guides and transport for all of it.',
      away: 'away', drive: 'drive', km: 'km', minsUnit: 'min',
    },
    faqPage: {
      pageTitle: 'Questions & Answers', pageSub: 'The things guests ask us most — answered honestly.',
    },
    myb: {
      pageTitle: 'My Booking', pageSub: 'Enter your booking reference and phone number to view your stay.',
      refLbl: 'Booking Reference', phoneLbl: 'Phone Number', find: 'Find My Booking',
      notFound: 'No booking found with that reference. Try NR-1040.',
      yourStay: 'Your Stay', billing: 'Billing', statusLbl: 'Status',
      payNow: 'Pay Outstanding Now', payTitle: 'Pay with', method: 'Choose a method',
      mobileNo: 'Mobile Number', pin: 'PIN', payBtn: 'Pay',
      paySuccess: 'Payment received!', receiptNo: 'Receipt No.',
      backSearch: '← Look up another booking', settled: 'Fully paid — see you soon!',
      cardNo: 'Card Number', payNote: 'This is a demo — no real money moves.',
    },
    reviews: {
      pageTitle: 'Share Your Experience', pageSub: 'Stayed with us? Your words guide our next guest — and our team reads every one.',
      formTitle: 'Write a Review', name: 'Your Name', villa: 'Which villa did you stay in?',
      rating: 'Your Rating', comment: 'Your Review', commentPh: 'What did you love? What can we do better?',
      submit: 'Submit Review',
      thanks: 'Thank you! Your review has been sent to our team.',
      recent: 'Recent Guest Reviews',
    },
    chat: {
      title: 'Cumilla Help', hello: 'Hello! How can we help? Pick a question:',
      qs: ['What are the room rates?', 'How do I reach you?', 'Is food halal?', 'How do I book?'],
      as: [
        'Villas start at ৳12,500/night (Lalmai Hill Villa) up to ৳35,000 (Suite). See the Villas page or Live Availability for dates.',
        'Bus or train from Dhaka to Cumilla (~2 hrs), or drive (~1.5 hrs). We arrange station pickup.',
        'Yes — fully halal kitchens, with vegan and vegetarian menus too.',
        'Use the Book Now button, or call +880 1711 555 123. A 30% advance confirms your stay.',
      ],
      whatsapp: 'Chat on WhatsApp',
    },
    avail: {
      pageTitle: 'Live Room Availability', pageSub: 'Pick your dates — see exactly which villas are free, updated live.',
      liveNow: 'Live', from: 'Check In', to: 'Check Out', check: 'Check',
      available: 'Available', booked: 'Booked', summary: 'available for your dates',
      bookedRanges: 'Booked:', allFree: 'No bookings in this window', bookThis: 'Book',
      ofRooms: 'of', roomsFree: 'villas free', forDates: 'For',
      invalidRange: 'Check-out must be after check-in.',
    },
    common: {
      perNight: '/ night', guests: 'Guests', bedrooms: 'Bedrooms', viewDetails: 'View Details',
      reserve: 'Reserve', bookYourStay: 'Book Your Stay', exploreMore: 'Explore More',
      learnMore: 'Learn More', viewAll: 'View All', from: 'From', taka: '৳',
      checkIn: 'Check In', checkOut: 'Check Out', villaType: 'Villa Type', anyVilla: 'Any Available',
      checkAvailability: 'Check Availability', send: 'Send', name: 'Name', email: 'Email',
      phone: 'Phone', message: 'Message', subscribe: 'Join', back: 'Back', next: 'Next',
      confirm: 'Confirm Booking', night: 'night', nights: 'nights', total: 'Total',
      adults: 'Adults', children: 'Children', search: 'Search', demoNote: 'Demo only — no real data is sent.',
      scroll: 'Scroll', backToTop: 'Back to top',
    },
    home: {
      heroEyebrow: 'Cumilla Resort · Kotbari, Cumilla',
      heroTitle1: 'Where Red Clay Hills',
      heroTitleEm: 'Whisper',
      heroTitle2: 'and History Comes Alive',
      heroSub: 'An eco-luxury sanctuary nestled among the scenic Lalmai Hills and ancient archaeological wonders of Kotbari, Cumilla — where nature meets heritage.',
      reserveEscape: 'Reserve Your Escape', exploreVillas: 'Explore Villas',
      stats: { villas: 'Private Villas', acres: 'Acres of Hillside Gardens', years: 'Years of Hospitality', rate: '% Guest Return Rate' },
      aboutEyebrow: 'Our Sanctuary',
      aboutTitle1: 'A Resort Grown', aboutTitleEm: 'From', aboutTitle2: 'the Heritage of Terracotta and Hills',
      aboutLead: 'Every villa at Cumilla Resort is built with local terracotta tiles and reclaimed timber, powered by the sun and fed by our own organic gardens — set within 45 acres of scenic hills beside Shalban Vihara.',
      f1t: '100% Solar Powered', f1d: 'Our entire estate runs on renewable energy harvested on-site.',
      f2t: 'Garden-to-Table Dining', f2d: 'Bengali cuisine fed daily by our organic gardens and local haors.',
      f3t: 'Guided Heritage Trails', f3d: 'Dawn walks through Lalmai trails and ancient archaeological ruins with our local guides.',
      award: 'South Asia Travel Award', awardSub: 'Best Eco Resort 2025',
      villasEyebrow: 'Stay With Us', villasTitle1: 'Villas &', villasTitleEm: 'Cottages',
      villasLead: 'Thirty-two sanctuaries scattered between scenic slopes and ancient forests — each with a private veranda and a view that never repeats itself.',
      expEyebrow: 'Beyond the Room', expTitle1: 'Curated', expTitleEm: 'Experiences',
      galleryEyebrow: 'Moments at Cumilla Resort', galleryTitle: 'The', galleryTitleEm: 'Gallery',
      galleryLead: 'Hover to pause. Every frame photographed on and around the estate.',
      testiEyebrow: 'Guest Stories', testiTitle1: 'Loved by', testiTitleEm: 'Travellers', testiTitle2: 'Everywhere',
      ctaEyebrow: 'Begin Your Journey', ctaTitle1: 'Your Villa Is', ctaTitleEm: 'Waiting',
      ctaLead: 'Check availability for your dates — our reservations team confirms within the hour.',
    },
    villas: {
      pageTitle: 'Villas & Cottages', pageSub: 'Thirty-two private sanctuaries between scenic hills and ancient forests.',
      amenities: 'Amenities', overview: 'Overview', priceFrom: 'From', whatsIncluded: "What's Included",
      checkDates: 'Check Dates', otherVillas: 'Other Villas You May Like',
      included: ['Daily à la carte breakfast', 'Evening Roshomalai service', 'Guided Mainamati Vihara walk', 'Station pickup (on request)'],
    },
    experiences: {
      pageTitle: 'Experiences', pageSub: 'Tea, forest, lake and culture — curated by our resident naturalists.',
      duration: 'Duration', difficulty: 'Difficulty', includes: 'Includes', bookExp: 'Book This Experience',
      easy: 'Easy', moderate: 'Moderate',
    },
    dining: {
      pageTitle: 'Dining', pageSub: 'Bengali heritage cooking, estate-grown tea and fire-lit evenings.',
      hours: 'Hours', cuisine: 'Cuisine', signature: 'Signature Dishes', reserveTable: 'Reserve a Table',
    },

    gallery: {
      pageTitle: 'Gallery', pageSub: 'Photographed on and around the estate, in every season.',
      all: 'All', nature: 'Nature', villas: 'Villas', dining: 'Dining',
    },
    about: {
      pageTitle: 'Our Story', pageSub: 'Fourteen years of slow hospitality in the historic hills of Cumilla.',
      storyEyebrow: 'Since 2012',
      storyTitle1: 'Born in the', storyTitleEm: 'Red Clay Hills',
      story1: 'Cumilla Resort began as a single terracotta cottage on a quiet hillside, built by the Rahman family so that travellers could wake to the peaceful mist over Lalmai.',
      story2: 'Today we are thirty-two villas and three restaurants — but the promise is unchanged: nothing we build may rise above the trees, and nothing we serve may travel further than the hills you can see.',
      valuesTitle: 'What We Stand For',
      values: [
        { t: 'Protect the Heritage', d: 'We support preservation of archaeological sites and local forestry around Kotbari.' },
        { t: 'Employ the Hills', d: '92% of our team comes from villages within ten kilometres.' },
        { t: 'Grow, Not Truck', d: 'Our gardens and local haors supply over 80% of every menu.' },
        { t: 'Slow Hospitality', d: 'Fewer guests, longer stays, deeper rest. We never overbuild.' },
      ],
      teamTitle: 'The People of Cumilla Resort',
      awardsTitle: 'Recognition',
      awards: ['Best Eco Resort — South Asia Travel Awards 2025', 'Top 10 Forest Stays in Asia — Wanderlust 2024', 'Green Hospitality Gold — Bangladesh Tourism Board 2023'],
    },
    offers: {
      pageTitle: 'Seasonal Offers', pageSub: 'Packages woven around the seasons of the tea garden.',
      validTill: 'Valid till', bookOffer: 'Book This Offer', perCouple: 'per couple', perFamily: 'per family',
    },
    contact: {
      pageTitle: 'Contact Us', pageSub: 'We reply within the hour, every day from 8am to 10pm.',
      address: 'Address', addressVal: 'Kotbari Road, Shalban Vihara, Cumilla 3500, Bangladesh',
      phoneTitle: 'Phone', emailTitle: 'Email', formTitle: 'Send Us a Message',
      mapTitle: 'Find Us', getDirections: 'Get Directions', sent: 'Thank you! Our team will reply within the hour. (Demo)',
      msgPlaceholder: 'Tell us about your dates, group size, or any special occasion…',
    },
    booking: {
      pageTitle: 'Book Your Stay', pageSub: 'Four quick steps — confirmation within the hour.',
      steps: ['Dates & Guests', 'Choose Villa', 'Your Details', 'Review'],
      selectVilla: 'Select a villa', stayLength: 'Length of stay', summary: 'Booking Summary',
      villa: 'Villa', dates: 'Dates', priceNight: 'Price / night', special: 'Special requests (optional)',
      specialPh: 'Honeymoon decoration, dietary needs, early check-in…',
      confirmedTitle: 'Booking Request Received!',
      confirmedSub: 'Our reservations team will confirm by phone and email within the hour. Your reference:',
      backHome: 'Back to Home', payNote: 'No payment needed now — pay at the resort or via bKash link after confirmation.',
    },
    testimonials: [
      { quote: '“We woke to mist over the Lalmai Hills and the tranquil sounds of nature near Shalban Vihara. Cumilla Resort is not a hotel — it is a feeling I have been chasing ever since.”', name: 'Ayesha Karim', where: 'Dhaka, Bangladesh' },
      { quote: '“The seven-layer tea, the lantern-lit dinner in the garden, the rain on the bamboo roof — the most romantic week of our marriage.”', name: 'Daniel Okafor', where: 'Lagos, Nigeria' },
      { quote: '“Travelled with three kids and it still felt serene. The birdwatching walks were the highlight of their year — and ours.”', name: 'Sofia Lindqvist', where: 'Stockholm, Sweden' },
    ],
    footer: {
      blurb: 'An eco-luxury resort set within 45 acres of scenic hills beside Shalban Vihara, Kotbari, Cumilla.',
      explore: 'Explore', contactTitle: 'Contact', newsletter: 'Newsletter',
      newsBlurb: 'Seasonal offers and stories from the heritage hills, once a month.',
      emailPh: 'Your email address', staffPortal: 'Staff Portal →',
      rights: '© 2026 Cumilla Resort. Demo Project Developed By Mahfuzur Rahman',
      mgmtDash: 'Management Dashboard',
    },
    admin: {
      sidebar: {
        operations: 'Operations', resort: 'Resort', guestcare: 'Guest Care',
        dashboard: 'Dashboard', bookings: 'Bookings', calendar: 'Booking Calendar', rent: 'Room Renting', rooms: 'Villas & Rooms', guests: 'Guests',
        frontdesk: 'Front Desk', prebooking: 'Pre-Booking', dues: 'Dues Collection', membership: 'Membership', feedback: 'Feedback',
        housekeeping: 'Housekeeping', staff: 'Staff', hr: 'HR & Payroll', finance: 'Finance & Accounts',
        inventory: 'Inventory & Stock', pos: 'Restaurant POS',
        cms: 'Site Content (CMS)', reports: 'Reports', settings: 'Settings', roles: 'Role Permissions',
        viewSite: 'View Public Site', signOut: 'Sign Out',
      },
      login: {
        title: 'Staff Portal', sub: 'Sign in to Cumilla Resort Management', email: 'Work Email',
        password: 'Password', signIn: 'Sign In', hint: 'Demo: any email and password works.',
        backSite: '← Back to public site',
        signInAs: 'Sign in as', roleSuperadmin: 'Super Admin', roleGm: 'General Manager', roleFrontdesk: 'Front Desk', roleHousekeeping: 'Housekeeping',
        roleSuperadminHint: 'Full system access & custom permissions config',
        roleGmHint: 'Full access — every module', roleFrontdeskHint: 'Bookings, guests, front desk & billing',
        roleHousekeepingHint: 'Tasks, rooms & cleaning log only',
      },
      roles: {
        title: 'Role & Permissions', sub: 'Create custom roles and select menu page access permissions',
        nameLbl: 'Role Name', iconLbl: 'Icon Style', hintLbl: 'Description (Hint)',
        createBtn: 'Create Custom Role', resetBtn: 'Reset to Defaults',
        saveBtn: 'Save Permissions', deleteBtn: 'Delete Custom Role',
        namePh: 'e.g. Receptionist', hintPh: 'e.g. Can view check-ins and billing',
        allPages: 'All Pages & Menus', selectAccess: 'Select Page Access',
        createdSuccess: 'Custom role created successfully.',
        savedSuccess: 'Role permissions saved.',
        deletedSuccess: 'Role deleted.',
        resetSuccess: 'Permissions reset to defaults.'
      },
      inventory: {
        title: 'Inventory & Stock', sub: 'Kitchen, housekeeping, maintenance & garden supplies',
        totalItems: 'Stock Items', lowStock: 'Low Stock Alerts', stockValue: 'Stock Value', supplierCount: 'Suppliers',
        itemsTitle: 'Stock Items', itemsHint: 'Items at or below reorder level are flagged red',
        item: 'Item', category: 'Category', unit: 'Unit', stock: 'In Stock', reorderLv: 'Reorder Level',
        unitPrice: 'Unit Price', value: 'Value', supplier: 'Supplier', ok: 'OK', low: 'Low Stock',
        cats: { kitchen: 'Kitchen', housekeeping: 'Housekeeping', maintenance: 'Maintenance' },
        suppliersTitle: 'Suppliers', suppliersHint: 'Approved vendors', contact: 'Contact',
        poTitle: 'Purchase Orders', poHint: 'Recent orders · pending arrive within 48 hrs', poRef: 'PO Ref',
        itemsCol: 'Items', newPO: 'New Purchase Order',
      },
      pos: {
        title: 'Restaurant POS', sub: 'Take orders — post straight to the room bill',
        todaySales: "Today's F&B Sales", orderCount: 'Orders Today', openFolios: 'Open Room Folios',
        menuTitle: 'Menu', menuHint: 'Tap an item to add it to the order',
        orderTitle: 'Current Order', orderHint: 'Choose a guest, then add items',
        selectGuest: 'Charge to', walkIn: 'Walk-in (cash)', qty: 'Qty',
        postRoom: 'Post to Room Bill', cashPay: 'Cash Payment', clearOrder: 'Clear',
        posted: 'Posted to the room folio.', paidMsg: 'Cash payment recorded. (Demo)',
        noOrder: 'No items yet — tap the menu', orderTotal: 'Order Total',
        folioTitle: 'Room Folios (In-house Guests)', folioHint: 'Room-service charges — added to the invoice at checkout',
        folioTotal: 'Folio Total', noCharges: 'No charges yet',
        cats: { food: 'Food', beverage: 'Beverages', dessert: 'Desserts' },
      },
      top: {
        searchPh: 'Search bookings, guests, villas…', notifications: 'Notifications',
        greeting: 'Good morning', gm: 'General Manager',
      },
      dash: {
        sub: 'Wednesday, 10 June 2026 · Cumilla Resort',
        occupancy: 'Occupancy', revenueMtd: 'Revenue (MTD)', arrivals: 'Arrivals Today', requests: 'Open Requests',
        vsLastWeek: 'vs last week', vsLastMonth: 'vs May', checkedIn: 'checked in', expected: 'expected',
        urgent: 'urgent — maintenance', occupancyTrend: 'Occupancy Trend',
        trendHint: 'Villas occupied per night, last 12 nights', nights12: '12 Nights', nights30: '30 Nights', quarter: 'Quarter',
        occupied: 'Occupied villas', capacity: 'Capacity: 32 villas',
        revenueMix: 'Revenue Mix', mtd: 'Month to date', totalMtd: 'Total MTD',
        accommodation: 'Accommodation', diningRev: 'Dining', expRev: 'Experiences',
        recentBookings: 'Recent Bookings', recentHint: 'Latest reservations across all channels',
        newBooking: 'New Booking', todayCheckins: "Today's Check-ins", arrivalsLeft: 'arrivals remaining',
        teaVillas: 'Lalmai Hill', treehouses: 'Terracotta Cottage', cottages: 'Dharmasagar Cottage',
      },
      table: {
        guest: 'Guest', villa: 'Villa', dates: 'Dates', total: 'Total', status: 'Status',
        ref: 'Ref', checkIn: 'Check In', checkOut: 'Check Out', channel: 'Channel',
        stay: 'Stay', preferences: 'Preferences', spend: 'Spend', tier: 'Tier',
        task: 'Task', team: 'Team', priority: 'Priority', due: 'Due',
        role: 'Role', shift: 'Shift', department: 'Department',
      },
      status: {
        confirmed: 'Confirmed', pending: 'Pending', checkedIn: 'Checked In', cancelled: 'Cancelled',
        checkedOut: 'Checked Out', occupied: 'Occupied', arriving: 'Arriving', vacant: 'Vacant',
        maintenance: 'Maintenance', inProgress: 'In Progress', queued: 'Queued', done: 'Done',
        withVendor: 'With Vendor', urgent: 'Urgent', high: 'High', normal: 'Normal',
        onDuty: 'On Duty', offDuty: 'Off Duty', onLeave: 'On Leave',
        gold: 'Gold', silver: 'Silver', platinum: 'Platinum', booked: 'booked', star: 'Star',
        open: 'Open', resolved: 'Resolved', advancePaid: 'Advance Paid', awaitingAdvance: 'Awaiting Advance',
        complaint: 'Complaint', praise: 'Praise', suggestion: 'Suggestion',
        partial: 'Partially Paid', paid: 'Paid', expectedToday: 'Expected',
      },
      bookings: {
        title: 'Bookings', sub: 'Manage reservations across all channels',
        all: 'All', listTitle: 'All Bookings', listHint: 'reservations · June 2026',
        searchPh: 'Search by guest or reference…',
        detailTitle: 'Booking Details', invoiceTitle: 'Invoice', billingTitle: 'Billing & Payment',
        guestInfo: 'Guest Information', roomInfo: 'Room Information', stayInfo: 'Stay Details',
        checkIn: 'Check In', checkOut: 'Check Out', nights: 'Nights',
        roomRate: 'Room Rate/Night', subtotal: 'Subtotal', taxRate: 'Tax (10%)',
        discount: 'Discount', total: 'Total Amount', paidAmount: 'Paid', pendingAmount: 'Pending',
        paymentStatus: 'Payment Status', paid: 'Paid', pending: 'Pending', partial: 'Partially Paid', cancelled: 'Cancelled',
        invoiceNo: 'Invoice No.', invoiceDate: 'Invoice Date', dueDate: 'Due Date',
        guestEmail: 'Email', guestPhone: 'Phone', guestAddress: 'Address',
        roomType: 'Room Type', roomNo: 'Room Number', amenities: 'Amenities',
        bookingChannel: 'Booking Channel', specialRequests: 'Special Requests',
      },
      rooms: {
        title: 'Villas & Rooms', sub: 'Live status across 32 villas',
        liveTitle: 'Live Villa Status', liveHint: '32 villas · tap a villa for details',
        catTitle: 'Villa Categories', catHint: 'Rates & inventory', units: 'units',
      },
      guests: {
        title: 'Guests', sub: 'Profiles & preferences for guests on property',
        dirTitle: 'Guest Directory', dirHint: 'Guests currently on property', addGuest: 'Add Guest',
        profileTitle: 'Guest Record', contact: 'Contact Information', phone: 'Phone', email: 'Email',
        idDoc: 'ID Document', memberSince: 'Guest Since', totalVisits: 'Total Visits',
        totalSpend: 'Lifetime Spend', currentStay: 'Current Stay',
        historyTitle: 'Stay History', historyHint: 'Every stay on record, newest first',
        notesTitle: 'Staff Notes', viewRecord: 'View Record', backToList: '← All guests',
      },
      rent: {
        title: 'Room Renting', sub: 'Walk-in & phone rentals — live bill calculation',
        formTitle: 'New Room Rental', formHint: 'Fill in guest and room details — the bill updates live',
        guestName: 'Guest Name', guestPhone: 'Phone Number', villaType: 'Villa Type',
        checkInDate: 'Check-in Date', nights: 'Nights', adults: 'Adults',
        extras: 'Extra Services', discount: 'Discount (৳)',
        billTitle: 'Bill Summary', roomCharge: 'Room Charge', extrasCharge: 'Extras',
        confirmBtn: 'Confirm Rental', successTitle: 'Rental Confirmed!',
        successSub: 'Booking reference', another: 'New Rental',
        namePh: 'e.g. Rahim Uddin', phonePh: 'e.g. +880 17XX XXXXXX',
        nightsUnit: 'night(s)', fillWarn: 'Please enter guest name and phone number.',
      },
      charges: {
        title: 'Room Charge Management', hint: 'Nightly rates and add-on charges — edit and save',
        baseRate: 'Base Rate / Night', weekendRate: 'Weekend Rate', extraTitle: 'Add-on Charges',
        extraHint: 'Chargeable extra services', service: 'Service', charge: 'Charge',
        perNight: '/ night', perPerson: '/ person', perTrip: '/ trip', perUse: '/ use',
        save: 'Save Charges', saved: 'Charges updated. (Demo)',
      },
      frontdesk: {
        title: 'Front Desk', sub: 'One-click check-in & checkout — today, 11 June 2026',
        arrivalsToday: 'Arrivals Today', departuresToday: 'Departures Today', inHouse: 'Guests In-House', occNow: 'Occupancy Now',
        arrivalsTitle: 'Arrival Queue', arrivalsHint: 'Expected guests — tap to register arrival',
        departuresTitle: 'Departure Queue', departuresHint: 'Checkouts due by 12:00 — settle dues at checkout',
        checkInBtn: 'Check In', checkOutBtn: 'Check Out', checkedInDone: 'Checked in',
        checkedOutDone: 'Checked out', dueAtCheckout: 'Due at Checkout', noDue: 'Settled',
        eta: 'ETA', etd: 'Departure',
      },
      prebooking: {
        title: 'Pre-Booking', sub: 'Advance reservations for future dates',
        listTitle: 'Upcoming Reservations', listHint: 'July – December 2026 · 30% advance secures the booking',
        kpiTotal: 'Pre-Bookings', kpiAdvance: 'Advance Collected', kpiAwaiting: 'Awaiting Advance', kpiValue: 'Future Revenue Booked',
        advance: 'Advance (30%)', balance: 'Balance Due', collectAdvance: 'Collect Advance',
      },
      dues: {
        title: 'Dues Collection', sub: 'Outstanding guest balances in one place',
        listTitle: 'Outstanding Bills', listHint: 'Bookings with unpaid balance · June 2026',
        totalOutstanding: 'Total Outstanding', duesCount: 'Guests with Dues', collectedMtd: 'Collected (MTD)',
        collectBtn: 'Collect', collectedMsg: 'Marked as collected. (Demo)',
        billTotal: 'Bill Total', alreadyPaid: 'Paid So Far',
      },
      membership: {
        title: 'Membership & Loyalty', sub: 'Star · Gold · Platinum tiers with loyalty points',
        tiersTitle: 'Membership Tiers', tiersHint: 'Earn 1 point per ৳100 spent — tier upgrades are automatic',
        membersTitle: 'Members', membersHint: 'All enrolled guests, highest points first',
        member: 'Member', points: 'Points', tier: 'Tier', benefits: 'Benefits',
        pointsRange: 'Points Range', andAbove: 'and above', upTo: 'up to',
        sinceLbl: 'Since', visitsLbl: 'Visits', spendLbl: 'Lifetime Spend',
        totalMembers: 'Total Members', platinumCount: 'Platinum', goldCount: 'Gold', starCount: 'Star',
      },
      feedback: {
        title: 'Feedback & Complaints', sub: 'Guest feedback log with resolution tracking',
        listTitle: 'Feedback Log', listHint: 'Newest first · resolve complaints from here',
        openCount: 'Open Complaints', resolvedCount: 'Resolved', avgRating: 'Average Rating', totalCount: 'Total Entries',
        type: 'Type', rating: 'Rating', resolveBtn: 'Mark Resolved', resolvedMsg: 'Marked as resolved.',
      },
      housekeeping: {
        title: 'Housekeeping', sub: 'Daily task queue & team assignments',
        queueTitle: 'Housekeeping Queue', queueHint: "Today's schedule · 4 teams on duty", assign: 'Assign Task',
        logTitle: 'Cleaning Log', logHint: 'Who cleaned which villa today', cleaner: 'Cleaned By',
        duration: 'Duration', condition: 'Room Condition', inspection: 'Inspection',
        good: 'Good', fair: 'Fair', needsRepair: 'Needs Repair', inspected: 'Inspected', pendingInsp: 'Pending',
        mins: 'min', condSummary: 'Room Condition Summary',
      },
      staff: {
        title: 'Staff', sub: 'Team roster, shifts and departments',
        rosterTitle: 'Team Roster', rosterHint: '12 staff · 8 departments', addStaff: 'Add Staff',
        morning: 'Morning (6am–2pm)', evening: 'Evening (2pm–10pm)', nightShift: 'Night (10pm–6am)',
      },
      hr: {
        title: 'HR & Payroll', sub: 'Roster plan, attendance, overtime & salaries',
        totalStaff: 'Total Staff', onDutyToday: 'On Duty Today', onLeaveNow: 'On Leave',
        payrollCost: 'Payroll This Month', otThisMonth: 'Overtime (MTD)',
        tabRoster: 'Roster Plan', tabAttendance: 'Attendance & Hours', tabPayroll: 'Payroll',
        rosterTitle: 'Weekly Roster Plan', rosterHint: 'Shift plan · 12 staff · 7–13 June 2026',
        days: ['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        shiftM: 'Morning', shiftE: 'Evening', shiftN: 'Night', shiftO: 'Off',
        attTitle: 'Attendance & Duty Hours', attHint: 'June 2026 · month to date',
        daysWorked: 'Days', hoursWorked: 'Hours', otHours: 'OT Hours', lateDays: 'Late', leaveDays: 'Leave',
        payTitle: 'Payroll — June 2026', payHint: 'Base salary, overtime and net pay',
        baseSalary: 'Base Salary', otRate: 'OT Rate/hr', otPay: 'OT Pay', deduction: 'Deduction', netPay: 'Net Pay',
        paid: 'Paid', pendingPay: 'Pending', payslip: 'Payslip', hoursUnit: 'hrs',
      },
      finance: {
        title: 'Finance & Accounts',
        sub: 'Monthly income-expense analysis, P&L and transaction ledger',
        totalIncome: 'Total Income', totalExpense: 'Total Expense',
        netProfit: 'Net Profit', profitMargin: 'Profit Margin',
        vsLastMonth: 'vs last month',
        tabIncome: 'Income Analysis', tabExpense: 'Expense Analysis', tabLedger: 'Ledger',
        tabRates: 'Room Rates', tabRestaurants: 'Restaurants',
        incomeTitle: 'Income Breakdown — June 2026', incomeHint: 'Month to date · all revenue streams',
        expenseTitle: 'Expense Breakdown — June 2026', expenseHint: 'Month to date · vs monthly budget',
        ledgerTitle: 'Transaction Ledger', ledgerHint: 'Recent income & expense entries — June 2026',
        ratesTitle: 'Villa Rate Card & Occupancy', ratesHint: '6 villa types · nightly rates · June occupancy',
        restTitle: 'Restaurant Revenue & Margins', restHint: '3 dining venues · food cost analysis · June MTD',
        category: 'Category', amount: 'Amount', ofTotal: '% of Total',
        lastMonth: 'Last Month', change: 'Change',
        budget: 'Budget', variance: 'Variance', underBudget: 'Under Budget', overBudget: 'Over Budget',
        date: 'Date', ref: 'Reference', description: 'Description', type: 'Type',
        income: 'Income', expense: 'Expense', revenue: 'Revenue',
        plTitle: 'Monthly P&L — Last 6 Months', plHint: 'Revenue vs expense in lakhs BDT (৳L)',
        plMtdNote: 'June is month-to-date (first 10 days only)',
        villaType: 'Villa Type', nightRate: 'Night Rate', units: 'Units', occupancy: 'Occupancy',
        potentialRev: 'Potential Revenue', actualRev: 'Actual Revenue',
        restaurant: 'Restaurant', cuisine: 'Cuisine', guests: 'Guests',
        foodCost: 'Food Cost', avgBill: 'Avg Bill', margin: 'Margin', marginPct: 'Margin %',
        costPct: 'Food Cost %', growth: 'Growth vs May',
      },
      calendar: {
        title: 'Booking Calendar', sub: 'Month grid — every villa, every night, at a glance',
        legendBooked: 'Booked', legendFree: 'Free', legendToday: 'Today',
        clickHint: 'Click any free cell to start a new booking · hover a bar for guest & dates',
        room: 'Villa', months: ['June 2026', 'July 2026', 'August 2026'],
        occupancyOfMonth: 'Month occupancy',
      },
      notif: {
        title: 'Notifications', markAll: 'Mark all read', empty: 'All caught up!',
        unread: 'new',
      },
      cms: {
        title: 'Site Content (CMS)', sub: 'Control every public section — changes go live instantly',
        liveNote: 'Changes save automatically in this browser and appear on the public site immediately.',
        viewSite: 'Open Public Site', reset: 'Reset to Defaults',
        heroTitle: 'Homepage Hero', heroHint: 'Headline, subtitle and background image',
        imgUrl: 'Image URL', eyebrow: 'Eyebrow (small line above title)',
        titlePart1: 'Title — part 1', titleEm: 'Title — emphasized word', titlePart2: 'Title — part 2',
        subText: 'Subtitle', enLbl: 'English', bnLbl: 'বাংলা',
        menuTitle: 'Public Menu', menuHint: 'Show or hide items in the public navigation',
        navTitle: 'Public Menu Access', navHint: 'Enable or disable public menu items',
        sectionsTitle: 'Homepage Sections', sectionsHint: 'Toggle entire sections of the homepage',
        secTitle: 'Homepage Section Toggles', secHint: 'Enable or disable landing page sections',
        sec: {
          stats: 'Stats counters', about: 'About / story', villas: 'Villas preview',
          experiences: 'Experiences', custom: 'Custom sections', gallery: 'Gallery marquee',
          testimonials: 'Guest stories', cta: 'Booking call-to-action',
        },
        customTitle: 'Custom Showcase Sections', customHint: 'Add your own sections — image, title and description, in both languages',
        addSection: 'Add Section', removeSection: 'Remove', visible: 'Visible',
        secTitle: 'Section Title', secDesc: 'Description',
        newSecTitleEn: 'New Section', newSecTitleBn: 'নতুন সেকশন',
        newSecDescEn: 'Write a short description here…', newSecDescBn: 'এখানে সংক্ষিপ্ত বর্ণনা লিখুন…',
      },
      print: {
        btn: 'Print / PDF', generated: 'Generated', doc: 'Report',
        brandLine: 'Cumilla Resort · Kotbari, Cumilla, Bangladesh',
      },
      reports: {
        title: 'Reports', sub: 'Performance & revenue analytics',
        revpar: 'RevPAR', adr: 'ADR', avgStay: 'Avg Stay', rating: 'Guest Rating',
        yoy: 'YoY', reviews: 'reviews', stable: 'Stable vs 2025', nightsUnit: 'nts',
        monthlyTitle: 'Monthly Revenue', monthlyHint: 'Last 6 months · all revenue streams',
        channelTitle: 'Channel Performance', channelHint: 'Booking share by channel, June 2026',
        export: 'Export', topExp: 'Top Experiences', topExpHint: 'Bookings this month',
        directWeb: 'Direct Website', agents: 'Travel Agents', phone: 'Repeat / Phone',
        summaryTitle: 'Monthly Summary — June 2026', summaryHint: 'One-page overview across all operations',
        occAvg: 'Average Occupancy', revTotal: 'Total Revenue (MTD)', payrollTotal: 'Payroll Cost',
        tasksDone: 'Housekeeping Tasks Done', bookingsTotal: 'Bookings (MTD)', otTotal: 'Overtime Hours',
      },
      settings: {
        title: 'Settings', sub: 'Resort profile, rates and preferences',
        profile: 'Resort Profile', resortName: 'Resort Name', tagline: 'Tagline',
        taglineVal: 'Where history and hills meet', addr: 'Address',
        prefs: 'Preferences', defaultLang: 'Default Language', currency: 'Currency',
        checkInTime: 'Check-in Time', checkOutTime: 'Check-out Time',
        rates: 'Nightly Rates', notif: 'Notifications',
        notifList: ['Email on new booking', 'SMS on cancellation', 'Daily occupancy digest', 'Low-inventory alerts'],
        save: 'Save Changes', saved: 'Settings saved. (Demo)',
        english: 'English', bangla: 'Bangla',
        tplTitle: 'SMS / Email Templates', tplHint: 'Confirmation messages — {guest}, {villa}, {dates}, {ref}, {amount} are filled automatically',
        tplSave: 'Save Templates', tplSaved: 'Templates saved. (Demo)',
      },
    },
  },

  /* ================= BANGLA ================= */
  bn: {
    brand: { name: 'কুমিল্লা রিসোর্ট', full: 'কুমিল্লা রিসোর্ট', place: 'কোটবাড়ি, কুমিল্লা, বাংলাদেশ' },
    nav: {
      home: 'হোম', villas: 'ভিলা', experiences: 'অভিজ্ঞতা', dining: 'ডাইনিং',
      gallery: 'গ্যালারি', about: 'আমাদের কথা', offers: 'অফার',
      contact: 'যোগাযোগ', bookNow: 'বুক করুন', management: 'ব্যবস্থাপনা',
      availability: 'খালি রুম (লাইভ)', events: 'ইভেন্ট ও বিয়ে',
      explore: 'আশেপাশে', faq: 'প্রশ্নোত্তর', myBooking: 'আমার বুকিং', features: 'ফিচারসমূহ',
    },
    events: {
      pageTitle: 'ইভেন্ট ও বিয়ে', pageSub: 'চা বাগানে বিয়ে, বনের রিট্রিট আর বিশেষ দিন — শুরু থেকে শেষ পর্যন্ত আমাদের আয়োজনে।',
      includes: 'যা থাকছে', from: 'শুরু',
      inqTitle: 'আপনার ইভেন্ট পরিকল্পনা করুন', inqHint: 'উপলক্ষটা বলুন — আমাদের ইভেন্ট দল এক দিনের মধ্যে উত্তর দেবে।',
      name: 'আপনার নাম', phone: 'ফোন', date: 'পছন্দের তারিখ', type: 'ইভেন্টের ধরন',
      types: ['বিয়ে', 'কর্পোরেট রিট্রিট', 'জন্মদিন / বিশেষ দিন', 'অন্যান্য'],
      msg: 'বিস্তারিত লিখুন', send: 'ইনকোয়ারি পাঠান',
      sent: 'ধন্যবাদ! আমাদের ইভেন্ট দল ২৪ ঘণ্টার মধ্যে ফোন করবে। (ডেমো)',
    },
    explore: {
      pageTitle: 'কুমিল্লার আশেপাশে', pageSub: 'এক সকালের দূরত্বে কুমিল্লার সেরা সব জায়গা — গাইড ও যাতায়াত আমরাই ব্যবস্থা করি।',
      away: 'দূরে', drive: 'যাত্রা', km: 'কিমি', minsUnit: 'মিনিটের',
    },
    faqPage: {
      pageTitle: 'প্রশ্নোত্তর', pageSub: 'অতিথিরা যা সবচেয়ে বেশি জিজ্ঞেস করেন — সৎ উত্তরসহ।',
    },
    myb: {
      pageTitle: 'আমার বুকিং', pageSub: 'আপনার অবস্থান দেখতে বুকিং রেফারেন্স ও ফোন নম্বর দিন।',
      refLbl: 'বুকিং রেফারেন্স', phoneLbl: 'ফোন নম্বর', find: 'আমার বুকিং খুঁজুন',
      notFound: 'এই রেফারেন্সে কোনো বুকিং পাওয়া যায়নি। NR-1040 দিয়ে চেষ্টা করুন।',
      yourStay: 'আপনার অবস্থান', billing: 'বিলিং', statusLbl: 'অবস্থা',
      payNow: 'বকেয়া এখনই পরিশোধ করুন', payTitle: 'পরিশোধের মাধ্যম', method: 'একটি মাধ্যম বাছাই করুন',
      mobileNo: 'মোবাইল নম্বর', pin: 'পিন', payBtn: 'পরিশোধ করুন',
      paySuccess: 'পেমেন্ট গৃহীত হয়েছে!', receiptNo: 'রসিদ নম্বর',
      backSearch: '← অন্য বুকিং খুঁজুন', settled: 'সম্পূর্ণ পরিশোধিত — দেখা হবে শিগগিরই!',
      cardNo: 'কার্ড নম্বর', payNote: 'এটি ডেমো — আসল কোনো টাকা লেনদেন হয় না।',
    },
    reviews: {
      pageTitle: 'আপনার অভিজ্ঞতা জানান', pageSub: 'আমাদের সাথে ছিলেন? আপনার কথাই পরের অতিথির পথ দেখায় — আর আমাদের দল প্রতিটি রিভিউ পড়ে।',
      formTitle: 'রিভিউ লিখুন', name: 'আপনার নাম', villa: 'কোন ভিলায় ছিলেন?',
      rating: 'আপনার রেটিং', comment: 'আপনার রিভিউ', commentPh: 'কী ভালো লেগেছে? কোথায় আরও ভালো করতে পারি?',
      submit: 'রিভিউ জমা দিন',
      thanks: 'ধন্যবাদ! আপনার রিভিউ আমাদের দলের কাছে পৌঁছে গেছে।',
      recent: 'সাম্প্রতিক অতিথি রিভিউ',
    },
    chat: {
      title: 'কুমিল্লা হেল্প', hello: 'আসসালামু আলাইকুম! কীভাবে সাহায্য করতে পারি? একটি প্রশ্ন বাছাই করুন:',
      qs: ['রুমের ভাড়া কত?', 'কীভাবে আসব?', 'খাবার কি হালাল?', 'বুক করব কীভাবে?'],
      as: [
        'ভিলা শুরু ৳১২,৫০০/রাত (লালমাই হিল ভিলা) থেকে ৳৩৫,০০০ (স্যুট) পর্যন্ত। তারিখ অনুযায়ী দেখতে ভিলা বা খালি রুম (লাইভ) পেজ দেখুন।',
        'ঢাকা থেকে বাসে বা ট্রেনে কুমিল্লা (~২ ঘণ্টা) বা গাড়িতে (~দেড় ঘণ্টা)। আমরা স্টেশন থেকে পিকআপের ব্যবস্থা করি।',
        'হ্যাঁ — সম্পূর্ণ হালাল রান্নাঘর, ভেগান ও নিরামিষ মেনুও আছে।',
        '"বুক করুন" বাটন ব্যবহার করুন, অথবা ফোন করুন +৮৮০ ১৭১১ ৫৫৫ ১২৩। ৩০% অগ্রিমে বুকিং নিশ্চিত হয়।',
      ],
      whatsapp: 'হোয়াটসঅ্যাপে কথা বলুন',
    },
    avail: {
      pageTitle: 'লাইভ রুম স্ট্যাটাস', pageSub: 'তারিখ বাছাই করুন — কোন ভিলা খালি আছে দেখুন, লাইভ আপডেট।',
      liveNow: 'লাইভ', from: 'চেক ইন', to: 'চেক আউট', check: 'দেখুন',
      available: 'খালি', booked: 'বুকড', summary: 'আপনার তারিখে খালি',
      bookedRanges: 'বুকড:', allFree: 'এই সময়ে কোনো বুকিং নেই', bookThis: 'বুক করুন',
      ofRooms: 'এর মধ্যে', roomsFree: 'টি ভিলা খালি', forDates: 'তারিখ:',
      invalidRange: 'চেক-আউট অবশ্যই চেক-ইনের পরে হতে হবে।',
    },
    common: {
      perNight: '/ প্রতি রাত', guests: 'অতিথি', bedrooms: 'শয়নকক্ষ', viewDetails: 'বিস্তারিত দেখুন',
      reserve: 'রিজার্ভ করুন', bookYourStay: 'বুক করুন', exploreMore: 'আরও দেখুন',
      learnMore: 'আরও জানুন', viewAll: 'সব দেখুন', from: 'শুরু', taka: '৳',
      checkIn: 'চেক ইন', checkOut: 'চেক আউট', villaType: 'ভিলার ধরন', anyVilla: 'যেকোনো খালি ভিলা',
      checkAvailability: 'খালি আছে কিনা দেখুন', send: 'পাঠান', name: 'নাম', email: 'ইমেইল',
      phone: 'ফোন', message: 'বার্তা', subscribe: 'যুক্ত হোন', back: 'পেছনে', next: 'পরবর্তী',
      confirm: 'বুকিং নিশ্চিত করুন', night: 'রাত', nights: 'রাত', total: 'মোট',
      adults: 'প্রাপ্তবয়স্ক', children: 'শিশু', search: 'খুঁজুন', demoNote: 'ডেমো — কোনো প্রকৃত তথ্য পাঠানো হয় না।',
      scroll: 'স্ক্রল', backToTop: 'উপরে ফিরুন',
    },
    home: {
      heroEyebrow: 'কুমিল্লা রিসোর্ট · কোটবাড়ি, কুমিল্লা',
      heroTitle1: 'যেখানে লালমাটি পাহাড়',
      heroTitleEm: 'কথা বলে',
      heroTitle2: 'আর ইতিহাস জেগে ওঠে',
      heroSub: 'কোটবাড়ি, কুমিল্লার নয়নাভিরাম লালমাই পাহাড় এবং প্রাচীন প্রত্নতাত্ত্বিক ঐতিহ্যের মাঝে এক পরিবেশবান্ধব বিলাসবহুল আশ্রয় — যেখানে প্রকৃতির সাথে মিলেছে ইতিহাস।',
      reserveEscape: 'আপনার অবকাশ বুক করুন', exploreVillas: 'ভিলা দেখুন',
      stats: { villas: 'প্রাইভেট ভিলা', acres: 'একর পাহাড়ী বাগান', years: 'বছরের আতিথেয়তা', rate: '% অতিথি ফিরে আসেন' },
      aboutEyebrow: 'আমাদের আশ্রয়',
      aboutTitle1: 'টেরাকোটা ও পাহাড়ের', aboutTitleEm: 'ঐতিহ্যে', aboutTitle2: 'গড়ে ওঠা এক রিসোর্ট',
      aboutLead: 'কুমিল্লা রিসোর্টের প্রতিটি ভিলা তৈরি স্থানীয় টেরাকোটা ও পুরনো কাঠ দিয়ে — চলে সৌরশক্তিতে, খাবার আসে নিজস্ব জৈব বাগান থেকে। শালবন বিহারের পাশে ৪৫ একর পাহাড়ী ভূমির ভেতরে।',
      f1t: '১০০% সৌরবিদ্যুৎ', f1d: 'পুরো রিসোর্ট চলে নিজস্ব নবায়নযোগ্য শক্তিতে।',
      f2t: 'বাগান থেকে টেবিলে', f2d: 'নিজস্ব জৈব বাগান ও স্থানীয় হাওর থেকে প্রতিদিনের বাঙালি রান্না।',
      f3t: 'গাইডসহ ঐতিহ্যবাহী ট্রেইল', f3d: 'আমাদের গাইডের সাথে লালমাই পাহাড়ের ট্রেইল ও প্রাচীন প্রত্নতাত্ত্বিক ধ্বংসাবশেষ ঘুরে দেখার ভোরের চমৎকার অভিযান।',
      award: 'সাউথ এশিয়া ট্রাভেল অ্যাওয়ার্ড', awardSub: 'সেরা ইকো রিসোর্ট ২০২৫',
      villasEyebrow: 'আমাদের সাথে থাকুন', villasTitle1: 'ভিলা ও', villasTitleEm: 'কটেজ',
      villasLead: 'পাহাড়ের ঢাল আর বনের ছায়ায় ছড়িয়ে থাকা ৩২টি আশ্রয় — প্রতিটিতে নিজস্ব বারান্দা, আর এমন দৃশ্য যা কখনো এক রকম থাকে না।',
      expEyebrow: 'ঘরের বাইরে', expTitle1: 'বাছাই করা', expTitleEm: 'অভিজ্ঞতা',
      galleryEyebrow: 'কুমিল্লা রিসোর্টের মুহূর্ত', galleryTitle: 'ফটো', galleryTitleEm: 'গ্যালারি',
      galleryLead: 'থামাতে মাউস রাখুন। প্রতিটি ছবি রিসোর্ট ও আশপাশে তোলা।',
      testiEyebrow: 'অতিথিদের গল্প', testiTitle1: 'ভালোবাসায়', testiTitleEm: 'ভ্রমণপ্রেমীদের', testiTitle2: 'প্রিয়',
      ctaEyebrow: 'যাত্রা শুরু করুন', ctaTitle1: 'আপনার ভিলা', ctaTitleEm: 'অপেক্ষায়',
      ctaLead: 'আপনার তারিখে খালি আছে কিনা দেখুন — আমাদের রিজার্ভেশন দল এক ঘণ্টার মধ্যে নিশ্চিত করবে।',
    },
    villas: {
      pageTitle: 'ভিলা ও কটেজ', pageSub: 'পাহাড় আর বনের মাঝে ৩২টি প্রাইভেট আশ্রয়।',
      amenities: 'সুবিধাসমূহ', overview: 'সংক্ষিপ্ত বিবরণ', priceFrom: 'শুরু', whatsIncluded: 'যা যা অন্তর্ভুক্ত',
      checkDates: 'তারিখ দেখুন', otherVillas: 'আপনার পছন্দ হতে পারে এমন আরও ভিলা',
      included: ['প্রতিদিন আ-লা-কার্ত নাশতা', 'বিকেলের রসমলাই পরিবেশন', 'গাইডসহ ময়নামতি বিহার ভ্রমণ', 'স্টেশন থেকে পিকআপ (অনুরোধে)'],
    },
    experiences: {
      pageTitle: 'অভিজ্ঞতা', pageSub: 'পাহাড়, ঐতিহ্য, হ্রদ আর সংস্কৃতি — আমাদের গাইডের পরিকল্পনায়।',
      duration: 'সময়কাল', difficulty: 'কঠিনতা', includes: 'অন্তর্ভুক্ত', bookExp: 'এই অভিজ্ঞতা বুক করুন',
      easy: 'সহজ', moderate: 'মাঝারি',
    },
    dining: {
      pageTitle: 'ডাইনিং', pageSub: 'ঐতিহ্যবাহী বাঙালি রান্না, বাগানের চা আর আগুন-জ্বলা সন্ধ্যা।',
      hours: 'সময়', cuisine: 'রান্না', signature: 'বিশেষ পদ', reserveTable: 'টেবিল রিজার্ভ করুন',
    },

    gallery: {
      pageTitle: 'গ্যালারি', pageSub: 'প্রতিটি ঋতুতে রিসোর্ট ও আশপাশে তোলা ছবি।',
      all: 'সব', nature: 'প্রকৃতি', villas: 'ভিলা', dining: 'ডাইনিং',
    },
    about: {
      pageTitle: 'আমাদের গল্প', pageSub: 'কুমিল্লার ঐতিহাসিক পাহাড়ে চৌদ্দ বছরের ধীর আতিথেয়তা।',
      storyEyebrow: '২০১২ থেকে',
      storyTitle1: 'লালমাটি পাহাড়ে', storyTitleEm: 'জন্ম',
      story1: 'কুমিল্লা রিসোর্টের শুরু একটি মাত্র টেরাকোটা কটেজ দিয়ে — রহমান পরিবার চেয়েছিল, ভ্রমণকারীরা যেন ঘুম ভেঙে দেখে লালমাইয়ের পাহাড়ে কুয়াশা নামছে।',
      story2: 'আজ আমাদের ৩২টি ভিলা ও ৩টি রেস্তোরাঁ — কিন্তু প্রতিশ্রুতি বদলায়নি: গাছের চেয়ে উঁচু কিছু আমরা বানাই না, আর দৃষ্টিসীমার পাহাড়ের বাইরে থেকে কিছু পরিবেশন করি না।',
      valuesTitle: 'আমাদের অঙ্গীকার',
      values: [
        { t: 'ঐতিহ্য রক্ষা', d: 'কোটবাড়ির প্রত্নতাত্ত্বিক স্থান সংরক্ষণ ও স্থানীয় বন রক্ষায় আমরা সহযোগিতা করি।' },
        { t: 'পাহাড়ের মানুষ', d: 'আমাদের দলের ৯২% আসে দশ কিলোমিটারের মধ্যের গ্রাম থেকে।' },
        { t: 'ফলাই, আনাই না', d: 'প্রতিটি মেনুর ৮০%-এর বেশি আসে নিজস্ব বাগান ও স্থানীয় হাওর থেকে।' },
        { t: 'ধীর আতিথেয়তা', d: 'কম অতিথি, দীর্ঘ অবস্থান, গভীর বিশ্রাম। আমরা কখনো বাড়াবাড়ি করি না।' },
      ],
      teamTitle: 'কুমিল্লা রিসোর্টের মানুষেরা',
      awardsTitle: 'স্বীকৃতি',
      awards: ['সেরা ইকো রিসোর্ট — সাউথ এশিয়া ট্রাভেল অ্যাওয়ার্ডস ২০২৫', 'এশিয়ার সেরা ১০ হেরিটেজ স্টে — ওয়ান্ডারলাস্ট ২০২৪', 'গ্রিন হসপিটালিটি গোল্ড — বাংলাদেশ ট্যুরিজম বোর্ড ২০২৩'],
    },
    offers: {
      pageTitle: 'মৌসুমি অফার', pageSub: 'চা বাগানের ঋতু ঘিরে সাজানো প্যাকেজ।',
      validTill: 'মেয়াদ', bookOffer: 'এই অফার বুক করুন', perCouple: 'প্রতি দম্পতি', perFamily: 'প্রতি পরিবার',
    },
    contact: {
      pageTitle: 'যোগাযোগ', pageSub: 'প্রতিদিন সকাল ৮টা থেকে রাত ১০টা — এক ঘণ্টার মধ্যে উত্তর দিই।',
      address: 'ঠিকানা', addressVal: 'কোটবাড়ি রোড, শালবন বিহার, কুমিল্লা ৩৫০০, বাংলাদেশ',
      phoneTitle: 'ফোন', emailTitle: 'ইমেইল', formTitle: 'আমাদের বার্তা পাঠান',
      mapTitle: 'আমাদের অবস্থান', getDirections: 'দিকনির্দেশনা পান', sent: 'ধন্যবাদ! আমাদের দল এক ঘণ্টার মধ্যে উত্তর দেবে। (ডেমো)',
      msgPlaceholder: 'আপনার তারিখ, দলের আকার বা বিশেষ উপলক্ষ সম্পর্কে লিখুন…',
    },
    booking: {
      pageTitle: 'বুক করুন', pageSub: 'চারটি সহজ ধাপ — এক ঘণ্টার মধ্যে নিশ্চিতকরণ।',
      steps: ['তারিখ ও অতিথি', 'ভিলা বাছাই', 'আপনার তথ্য', 'পর্যালোচনা'],
      selectVilla: 'একটি ভিলা বাছাই করুন', stayLength: 'অবস্থানের দৈর্ঘ্য', summary: 'বুকিং সারসংক্ষেপ',
      villa: 'ভিলা', dates: 'তারিখ', priceNight: 'মূল্য / রাত', special: 'বিশেষ অনুরোধ (ঐচ্ছিক)',
      specialPh: 'হানিমুন সাজসজ্জা, খাবারের চাহিদা, আগাম চেক-ইন…',
      confirmedTitle: 'বুকিং অনুরোধ গৃহীত হয়েছে!',
      confirmedSub: 'আমাদের রিজার্ভেশন দল এক ঘণ্টার মধ্যে ফোন ও ইমেইলে নিশ্চিত করবে। আপনার রেফারেন্স:',
      backHome: 'হোমে ফিরুন', payNote: 'এখন কোনো পেমেন্ট লাগবে না — রিসোর্টে অথবা নিশ্চিতকরণের পরে বিকাশ লিংকে পরিশোধ করুন।',
    },
    testimonials: [
      { quote: '“ঘুম ভাঙল লালমাই পাহাড়ের কুয়াশায়, শালবনের শান্ত প্রকৃতির ডাকে। কুমিল্লা রিসোর্ট কোনো হোটেল নয় — এ এক অনুভূতি, যার পিছু আজও ছুটছি।”', name: 'আয়েশা করিম', where: 'ঢাকা, বাংলাদেশ' },
      { quote: '“সাত রঙের চা, বাগানে লণ্ঠন-জ্বলা ডিনার, বাঁশের ছাদে বৃষ্টির শব্দ — আমাদের দাম্পত্যের সবচেয়ে রোমান্টিক সপ্তাহ।”', name: 'ড্যানিয়েল ওকাফোর', where: 'লাগোস, নাইজেরিয়া' },
      { quote: '“তিন বাচ্চা নিয়ে গিয়েও মনে হলো প্রশান্তি। পাখি দেখার হাঁটা ছিল ওদের বছরের সেরা মুহূর্ত — আমাদেরও।”', name: 'সোফিয়া লিন্ডকভিস্ট', where: 'স্টকহোম, সুইডেন' },
    ],
    footer: {
      blurb: 'শালবন বিহারের পাশে ৪৫ একর পাহাড়ী অঞ্চলের ভেতরে এক পরিবেশবান্ধব বিলাসবহুল রিসোর্ট, কোটবাড়ি, কুমিল্লা।',
      explore: 'ঘুরে দেখুন', contactTitle: 'যোগাযোগ', newsletter: 'নিউজলেটার',
      newsBlurb: 'মাসে একবার — মৌসুমি অফার আর লালমাটি পাহাড়ের গল্প।',
      emailPh: 'আপনার ইমেইল ঠিকানা', staffPortal: 'স্টাফ পোর্টাল →',
      rights: '© ২০২৬ কুমিল্লা রিসোর্ট। ডেমো প্রজেক্ট ডেভেলপ করেছেন মাহফুজুর রহমান।',
      mgmtDash: 'ব্যবস্থাপনা ড্যাশবোর্ড',
    },
    admin: {
      sidebar: {
        operations: 'পরিচালনা', resort: 'রিসোর্ট', guestcare: 'অতিথিসেবা',
        dashboard: 'ড্যাশবোর্ড', bookings: 'বুকিং', calendar: 'বুকিং ক্যালেন্ডার', rent: 'রুম ভাড়া', rooms: 'ভিলা ও রুম', guests: 'অতিথি',
        frontdesk: 'ফ্রন্ট ডেস্ক', prebooking: 'প্রি-বুকিং', dues: 'বকেয়া আদায়', membership: 'মেম্বারশিপ', feedback: 'ফিডব্যাক',
        housekeeping: 'হাউসকিপিং', staff: 'কর্মী', hr: 'এইচআর ও বেতন', finance: 'আয়-ব্যয় হিসাব',
        inventory: 'ইনভেন্টরি ও স্টক', pos: 'রেস্টুরেন্ট POS',
        cms: 'সাইট কনটেন্ট', reports: 'রিপোর্ট', settings: 'সেটিংস', roles: 'রোল পারমিশন',
        viewSite: 'পাবলিক সাইট দেখুন', signOut: 'সাইন আউট',
      },
      login: {
        title: 'স্টাফ পোর্টাল', sub: 'কুমিল্লা রিসোর্ট ম্যানেজমেন্টে সাইন ইন করুন', email: 'অফিস ইমেইল',
        password: 'পাসওয়ার্ড', signIn: 'সাইন ইন', hint: 'ডেমো: যেকোনো ইমেইল ও পাসওয়ার্ড কাজ করবে।',
        backSite: '← পাবলিক সাইটে ফিরুন',
        signInAs: 'যে পরিচয়ে সাইন ইন করবেন', roleSuperadmin: 'সুপার এডমিন', roleGm: 'জেনারেল ম্যানেজার', roleFrontdesk: 'ফ্রন্ট ডেস্ক', roleHousekeeping: 'হাউসকিপিং',
        roleSuperadminHint: 'পূর্ণ সিস্টেম অ্যাক্সেস এবং কাস্টম পারমিশন কনফিগারেশন',
        roleGmHint: 'পূর্ণ অ্যাক্সেস — সব মডিউল', roleFrontdeskHint: 'বুকিং, অতিথি, ফ্রন্ট ডেস্ক ও বিলিং',
        roleHousekeepingHint: 'শুধু টাস্ক, রুম ও পরিচ্ছন্নতা লগ',
      },
      roles: {
        title: 'রোল ও পারমিশন', sub: 'কাস্টম রোল তৈরি করুন এবং পেজ ও মেনুর অ্যাক্সেস নিয়ন্ত্রণ করুন',
        nameLbl: 'রোল নাম', iconLbl: 'আইকন স্টাইল', hintLbl: 'বিবরণ (হিন্ট)',
        createBtn: 'কাস্টম রোল তৈরি করুন', resetBtn: 'ডিফল্টে ফিরুন',
        saveBtn: 'পারমিশন সংরক্ষণ করুন', deleteBtn: 'কাস্টম রোল মুছুন',
        namePh: 'যেমন: রিসেপশনিস্ট', hintPh: 'যেমন: চেক-ইন ও বিলিং দেখতে পারবেন',
        allPages: 'সব পেজ ও মেনু', selectAccess: 'পেজ অ্যাক্সেস নির্বাচন করুন',
        createdSuccess: 'কাস্টম রোল সফলভাবে তৈরি হয়েছে।',
        savedSuccess: 'রোল পারমিশন সংরক্ষিত হয়েছে।',
        deletedSuccess: 'রোল মুছে ফেলা হয়েছে।',
        resetSuccess: 'পারমিশন ডিফল্টে ফিরিয়ে আনা হয়েছে।'
      },
      inventory: {
        title: 'ইনভেন্টরি ও স্টক', sub: 'কিচেন, হাউসকিপিং, মেরামত ও বাগান সামগ্রী',
        totalItems: 'স্টক আইটেম', lowStock: 'কম স্টক সতর্কতা', stockValue: 'স্টকের মূল্য', supplierCount: 'সাপ্লায়ার',
        itemsTitle: 'স্টক আইটেম', itemsHint: 'রিঅর্ডার লেভেলে বা নিচে নামলে লাল চিহ্ন',
        item: 'আইটেম', category: 'ক্যাটাগরি', unit: 'একক', stock: 'মজুদ', reorderLv: 'রিঅর্ডার লেভেল',
        unitPrice: 'একক দাম', value: 'মূল্য', supplier: 'সাপ্লায়ার', ok: 'ঠিক আছে', low: 'কম স্টক',
        cats: { kitchen: 'কিচেন', housekeeping: 'হাউসকিপিং', maintenance: 'মেরামত' },
        suppliersTitle: 'সাপ্লায়ার', suppliersHint: 'অনুমোদিত বিক্রেতা', contact: 'যোগাযোগ',
        poTitle: 'পারচেজ অর্ডার', poHint: 'সাম্প্রতিক অর্ডার · অপেক্ষমাণগুলো ৪৮ ঘণ্টায় আসবে', poRef: 'পিও রেফারেন্স',
        itemsCol: 'আইটেমসমূহ', newPO: 'নতুন পারচেজ অর্ডার',
      },
      pos: {
        title: 'রেস্টুরেন্ট POS', sub: 'অর্ডার নিন — সরাসরি রুমের বিলে যোগ করুন',
        todaySales: 'আজকের খাবার বিক্রয়', orderCount: 'আজকের অর্ডার', openFolios: 'খোলা রুম ফোলিও',
        menuTitle: 'মেনু', menuHint: 'অর্ডারে যোগ করতে আইটেমে ক্লিক করুন',
        orderTitle: 'বর্তমান অর্ডার', orderHint: 'অতিথি বাছাই করে আইটেম যোগ করুন',
        selectGuest: 'বিল যাবে', walkIn: 'ওয়াক-ইন (নগদ)', qty: 'পরিমাণ',
        postRoom: 'রুমের বিলে যোগ করুন', cashPay: 'নগদ পেমেন্ট', clearOrder: 'মুছুন',
        posted: 'রুম ফোলিওতে যোগ হয়েছে।', paidMsg: 'নগদ পেমেন্ট রেকর্ড হয়েছে। (ডেমো)',
        noOrder: 'এখনো কোনো আইটেম নেই — মেনুতে ক্লিক করুন', orderTotal: 'অর্ডারের মোট',
        folioTitle: 'রুম ফোলিও (অবস্থানরত অতিথি)', folioHint: 'রুম-সার্ভিস চার্জ — চেক-আউটের ইনভয়েসে যোগ হবে',
        folioTotal: 'ফোলিওর মোট', noCharges: 'এখনো কোনো চার্জ নেই',
        cats: { food: 'খাবার', beverage: 'পানীয়', dessert: 'মিষ্টি' },
      },
      top: {
        searchPh: 'বুকিং, অতিথি, ভিলা খুঁজুন…', notifications: 'নোটিফিকেশন',
        greeting: 'শুভ সকাল', gm: 'জেনারেল ম্যানেজার',
      },
      dash: {
        sub: 'বুধবার, ১০ জুন ২০২৬ · কুমিল্লা রিসোর্ট',
        occupancy: 'অকুপেন্সি', revenueMtd: 'আয় (চলতি মাস)', arrivals: 'আজকের আগমন', requests: 'খোলা অনুরোধ',
        vsLastWeek: 'গত সপ্তাহের তুলনায়', vsLastMonth: 'মে মাসের তুলনায়', checkedIn: 'চেক ইন হয়েছে', expected: 'প্রত্যাশিত',
        urgent: 'জরুরি — রক্ষণাবেক্ষণ', occupancyTrend: 'অকুপেন্সি প্রবণতা',
        trendHint: 'প্রতি রাতে ভর্তি ভিলা, শেষ ১২ রাত', nights12: '১২ রাত', nights30: '৩০ রাত', quarter: 'ত্রৈমাসিক',
        occupied: 'ভর্তি ভিলা', capacity: 'ধারণক্ষমতা: ৩২ ভিলা',
        revenueMix: 'আয়ের উৎস', mtd: 'চলতি মাস', totalMtd: 'মোট (চলতি মাস)',
        accommodation: 'আবাসন', diningRev: 'ডাইনিং', expRev: 'অভিজ্ঞতা',
        recentBookings: 'সাম্প্রতিক বুকিং', recentHint: 'সব চ্যানেলের সর্বশেষ রিজার্ভেশন',
        newBooking: 'নতুন বুকিং', todayCheckins: 'আজকের চেক-ইন', arrivalsLeft: 'টি আগমন বাকি',
        teaVillas: 'লালমাই হিল', treehouses: 'টেরাকোটা কটেজ', cottages: 'ধর্মসাগর কটেজ',
      },
      table: {
        guest: 'অতিথি', villa: 'ভিলা', dates: 'তারিখ', total: 'মোট', status: 'অবস্থা',
        ref: 'রেফারেন্স', checkIn: 'চেক ইন', checkOut: 'চেক আউট', channel: 'চ্যানেল',
        stay: 'অবস্থান', preferences: 'পছন্দ', spend: 'খরচ', tier: 'স্তর',
        task: 'কাজ', team: 'দল', priority: 'অগ্রাধিকার', due: 'সময়সীমা',
        role: 'পদ', shift: 'শিফট', department: 'বিভাগ',
      },
      status: {
        confirmed: 'নিশ্চিত', pending: 'অপেক্ষমাণ', checkedIn: 'চেক ইন', cancelled: 'বাতিল',
        checkedOut: 'চেক আউট', occupied: 'ভর্তি', arriving: 'আসছে', vacant: 'খালি',
        maintenance: 'রক্ষণাবেক্ষণ', inProgress: 'চলছে', queued: 'অপেক্ষায়', done: 'সম্পন্ন',
        withVendor: 'ভেন্ডরের কাছে', urgent: 'জরুরি', high: 'উচ্চ', normal: 'সাধারণ',
        onDuty: 'কর্মরত', offDuty: 'ছুটিতে', onLeave: 'ছুটিতে',
        gold: 'গোল্ড', silver: 'সিলভার', platinum: 'প্লাটিনাম', booked: 'বুকড', star: 'স্টার',
        open: 'খোলা', resolved: 'সমাধান হয়েছে', advancePaid: 'অগ্রিম পরিশোধিত', awaitingAdvance: 'অগ্রিম বাকি',
        complaint: 'অভিযোগ', praise: 'প্রশংসা', suggestion: 'পরামর্শ',
        partial: 'আংশিক পরিশোধিত', paid: 'পরিশোধিত', expectedToday: 'প্রত্যাশিত',
      },
      bookings: {
        title: 'বুকিং', sub: 'সব চ্যানেলের রিজার্ভেশন ব্যবস্থাপনা',
        all: 'সব', listTitle: 'সব বুকিং', listHint: 'টি রিজার্ভেশন · জুন ২০২৬',
        searchPh: 'অতিথি বা রেফারেন্স দিয়ে খুঁজুন…',
        detailTitle: 'বুকিং বিবরণ', invoiceTitle: 'ইনভয়েস (চালান)', billingTitle: 'বিলিং ও পেমেন্ট',
        guestInfo: 'অতিথির তথ্য', roomInfo: 'রুমের তথ্য', stayInfo: 'অবস্থানের বিবরণ',
        checkIn: 'চেক ইন', checkOut: 'চেক আউট', nights: 'রাত',
        roomRate: 'রাত্রিকালীন দাম', subtotal: 'মোট (ট্যাক্স ছাড়া)', taxRate: 'ট্যাক্স (১০%)',
        discount: 'ছাড়', total: 'মোট পরিমাণ', paidAmount: 'পরিশোধিত', pendingAmount: 'বকেয়া',
        paymentStatus: 'পেমেন্ট অবস্থা', paid: 'পরিশোধিত', pending: 'বকেয়া', partial: 'আংশিক পরিশোধিত', cancelled: 'বাতিল',
        invoiceNo: 'ইনভয়েস নম্বর', invoiceDate: 'ইনভয়েস তারিখ', dueDate: 'প্রদেয় তারিখ',
        guestEmail: 'ইমেইল', guestPhone: 'ফোন', guestAddress: 'ঠিকানা',
        roomType: 'রুমের ধরন', roomNo: 'রুম নম্বর', amenities: 'সুবিধাসমূহ',
        bookingChannel: 'বুকিং চ্যানেল', specialRequests: 'বিশেষ অনুরোধ',
      },
      rooms: {
        title: 'ভিলা ও রুম', sub: '৩২টি ভিলার লাইভ অবস্থা',
        liveTitle: 'লাইভ ভিলা স্ট্যাটাস', liveHint: '৩২ ভিলা · বিস্তারিত দেখতে ভিলায় ক্লিক করুন',
        catTitle: 'ভিলা ক্যাটাগরি', catHint: 'ভাড়া ও মজুদ', units: 'টি',
      },
      guests: {
        title: 'অতিথি', sub: 'বর্তমানে অবস্থানরত অতিথিদের প্রোফাইল ও পছন্দ',
        dirTitle: 'অতিথি তালিকা', dirHint: 'বর্তমানে রিসোর্টে অবস্থানরত', addGuest: 'অতিথি যোগ করুন',
        profileTitle: 'অতিথির রেকর্ড', contact: 'যোগাযোগের তথ্য', phone: 'ফোন', email: 'ইমেইল',
        idDoc: 'পরিচয়পত্র', memberSince: 'অতিথি হয়েছেন', totalVisits: 'মোট ভিজিট',
        totalSpend: 'মোট খরচ (সর্বকাল)', currentStay: 'বর্তমান অবস্থান',
        historyTitle: 'অবস্থানের ইতিহাস', historyHint: 'রেকর্ডে থাকা সব অবস্থান, নতুনটি আগে',
        notesTitle: 'স্টাফ নোট', viewRecord: 'রেকর্ড দেখুন', backToList: '← সব অতিথি',
      },
      rent: {
        title: 'রুম ভাড়া', sub: 'ওয়াক-ইন ও ফোনে ভাড়া — সাথে সাথে বিলের হিসাব',
        formTitle: 'নতুন রুম ভাড়া', formHint: 'অতিথি ও রুমের তথ্য দিন — বিল সাথে সাথে আপডেট হবে',
        guestName: 'অতিথির নাম', guestPhone: 'ফোন নম্বর', villaType: 'ভিলার ধরন',
        checkInDate: 'চেক-ইন তারিখ', nights: 'রাত', adults: 'প্রাপ্তবয়স্ক',
        extras: 'অতিরিক্ত সেবা', discount: 'ছাড় (৳)',
        billTitle: 'বিলের সারসংক্ষেপ', roomCharge: 'রুম ভাড়া', extrasCharge: 'অতিরিক্ত সেবা',
        confirmBtn: 'ভাড়া নিশ্চিত করুন', successTitle: 'ভাড়া নিশ্চিত হয়েছে!',
        successSub: 'বুকিং রেফারেন্স', another: 'নতুন ভাড়া',
        namePh: 'যেমন: রহিম উদ্দিন', phonePh: 'যেমন: +৮৮০ ১৭XX XXXXXX',
        nightsUnit: 'রাত', fillWarn: 'অনুগ্রহ করে অতিথির নাম ও ফোন নম্বর দিন।',
      },
      charges: {
        title: 'রুম চার্জ ব্যবস্থাপনা', hint: 'রাত্রিকালীন ভাড়া ও অতিরিক্ত চার্জ — সম্পাদনা করে সংরক্ষণ করুন',
        baseRate: 'মূল ভাড়া / রাত', weekendRate: 'উইকেন্ড ভাড়া', extraTitle: 'অতিরিক্ত চার্জ',
        extraHint: 'অর্থের বিনিময়ে অতিরিক্ত সেবা', service: 'সেবা', charge: 'চার্জ',
        perNight: '/ রাত', perPerson: '/ জন', perTrip: '/ ট্রিপ', perUse: '/ বার',
        save: 'চার্জ সংরক্ষণ করুন', saved: 'চার্জ আপডেট হয়েছে। (ডেমো)',
      },
      frontdesk: {
        title: 'ফ্রন্ট ডেস্ক', sub: 'এক ক্লিকে চেক-ইন ও চেক-আউট — আজ, ১১ জুন ২০২৬',
        arrivalsToday: 'আজকের আগমন', departuresToday: 'আজকের প্রস্থান', inHouse: 'রিসোর্টে অতিথি', occNow: 'বর্তমান অকুপেন্সি',
        arrivalsTitle: 'আগমনের সারি', arrivalsHint: 'প্রত্যাশিত অতিথি — আগমন নিবন্ধনে ক্লিক করুন',
        departuresTitle: 'প্রস্থানের সারি', departuresHint: 'দুপুর ১২টার মধ্যে চেক-আউট — চেক-আউটের সময় বকেয়া মেটান',
        checkInBtn: 'চেক ইন', checkOutBtn: 'চেক আউট', checkedInDone: 'চেক ইন হয়েছে',
        checkedOutDone: 'চেক আউট হয়েছে', dueAtCheckout: 'চেক-আউটে বকেয়া', noDue: 'পরিশোধিত',
        eta: 'আগমন সময়', etd: 'প্রস্থান সময়',
      },
      prebooking: {
        title: 'প্রি-বুকিং', sub: 'ভবিষ্যৎ তারিখের অগ্রিম রিজার্ভেশন',
        listTitle: 'আসন্ন রিজার্ভেশন', listHint: 'জুলাই – ডিসেম্বর ২০২৬ · ৩০% অগ্রিমে বুকিং নিশ্চিত হয়',
        kpiTotal: 'প্রি-বুকিং', kpiAdvance: 'অগ্রিম আদায়', kpiAwaiting: 'অগ্রিম বাকি', kpiValue: 'ভবিষ্যৎ আয় বুকড',
        advance: 'অগ্রিম (৩০%)', balance: 'বাকি টাকা', collectAdvance: 'অগ্রিম নিন',
      },
      dues: {
        title: 'বকেয়া আদায়', sub: 'সব অতিথির বকেয়া এক জায়গায়',
        listTitle: 'বকেয়া বিল', listHint: 'অপরিশোধিত ব্যালেন্সসহ বুকিং · জুন ২০২৬',
        totalOutstanding: 'মোট বকেয়া', duesCount: 'বকেয়াসহ অতিথি', collectedMtd: 'আদায় (চলতি মাস)',
        collectBtn: 'আদায় করুন', collectedMsg: 'আদায় হিসেবে চিহ্নিত হয়েছে। (ডেমো)',
        billTotal: 'মোট বিল', alreadyPaid: 'এ পর্যন্ত পরিশোধিত',
      },
      membership: {
        title: 'মেম্বারশিপ ও লয়্যালটি', sub: 'স্টার · গোল্ড · প্লাটিনাম স্তর, লয়্যালটি পয়েন্টসহ',
        tiersTitle: 'মেম্বারশিপ স্তর', tiersHint: 'প্রতি ৳১০০ খরচে ১ পয়েন্ট — স্তর আপগ্রেড স্বয়ংক্রিয়',
        membersTitle: 'সদস্যরা', membersHint: 'নিবন্ধিত সব অতিথি, সর্বোচ্চ পয়েন্ট আগে',
        member: 'সদস্য', points: 'পয়েন্ট', tier: 'স্তর', benefits: 'সুবিধা',
        pointsRange: 'পয়েন্টের সীমা', andAbove: 'বা তার বেশি', upTo: 'পর্যন্ত',
        sinceLbl: 'সদস্য হয়েছেন', visitsLbl: 'ভিজিট', spendLbl: 'মোট খরচ',
        totalMembers: 'মোট সদস্য', platinumCount: 'প্লাটিনাম', goldCount: 'গোল্ড', starCount: 'স্টার',
      },
      feedback: {
        title: 'ফিডব্যাক ও অভিযোগ', sub: 'অতিথিদের মতামতের লগ, সমাধান ট্র্যাকিংসহ',
        listTitle: 'ফিডব্যাক লগ', listHint: 'নতুনটি আগে · অভিযোগ এখান থেকেই সমাধান করুন',
        openCount: 'খোলা অভিযোগ', resolvedCount: 'সমাধান হয়েছে', avgRating: 'গড় রেটিং', totalCount: 'মোট এন্ট্রি',
        type: 'ধরন', rating: 'রেটিং', resolveBtn: 'সমাধান হয়েছে চিহ্নিত করুন', resolvedMsg: 'সমাধান হিসেবে চিহ্নিত হয়েছে।',
      },
      housekeeping: {
        title: 'হাউসকিপিং', sub: 'দৈনিক কাজের তালিকা ও দল বণ্টন',
        queueTitle: 'হাউসকিপিং তালিকা', queueHint: 'আজকের সূচি · ৪টি দল কর্মরত', assign: 'কাজ বণ্টন করুন',
        logTitle: 'পরিচ্ছন্নতা লগ', logHint: 'আজ কে কোন ভিলা পরিষ্কার করলো', cleaner: 'পরিষ্কার করেছেন',
        duration: 'সময় লেগেছে', condition: 'রুমের অবস্থা', inspection: 'পরিদর্শন',
        good: 'ভালো', fair: 'মোটামুটি', needsRepair: 'মেরামত দরকার', inspected: 'পরিদর্শিত', pendingInsp: 'বাকি',
        mins: 'মিনিট', condSummary: 'রুমের অবস্থার সারসংক্ষেপ',
      },
      staff: {
        title: 'কর্মী', sub: 'টিম রোস্টার, শিফট ও বিভাগ',
        rosterTitle: 'টিম রোস্টার', rosterHint: '১২ জন কর্মী · ৮টি বিভাগ', addStaff: 'কর্মী যোগ করুন',
        morning: 'সকাল (৬টা–২টা)', evening: 'বিকাল (২টা–১০টা)', nightShift: 'রাত (১০টা–৬টা)',
      },
      hr: {
        title: 'এইচআর ও বেতন', sub: 'রোস্টার প্ল্যান, হাজিরা, ওভারটাইম ও বেতন',
        totalStaff: 'মোট কর্মী', onDutyToday: 'আজ কর্মরত', onLeaveNow: 'ছুটিতে',
        payrollCost: 'এ মাসের বেতন', otThisMonth: 'ওভারটাইম (চলতি মাস)',
        tabRoster: 'রোস্টার প্ল্যান', tabAttendance: 'হাজিরা ও ঘণ্টা', tabPayroll: 'বেতন',
        rosterTitle: 'সাপ্তাহিক রোস্টার প্ল্যান', rosterHint: 'শিফট পরিকল্পনা · ১২ জন কর্মী · ৭–১৩ জুন ২০২৬',
        days: ['শনি', 'রবি', 'সোম', 'মঙ্গল', 'বুধ', 'বৃহঃ', 'শুক্র'],
        shiftM: 'সকাল', shiftE: 'বিকাল', shiftN: 'রাত', shiftO: 'ছুটি',
        attTitle: 'হাজিরা ও ডিউটি ঘণ্টা', attHint: 'জুন ২০২৬ · চলতি মাস',
        daysWorked: 'দিন', hoursWorked: 'ঘণ্টা', otHours: 'ওভারটাইম', lateDays: 'দেরি', leaveDays: 'ছুটি',
        payTitle: 'বেতন — জুন ২০২৬', payHint: 'মূল বেতন, ওভারটাইম ও নিট বেতন',
        baseSalary: 'মূল বেতন', otRate: 'ওটি হার/ঘণ্টা', otPay: 'ওটি বেতন', deduction: 'কর্তন', netPay: 'নিট বেতন',
        paid: 'পরিশোধিত', pendingPay: 'বকেয়া', payslip: 'পে-স্লিপ', hoursUnit: 'ঘণ্টা',
      },
      finance: {
        title: 'আয়-ব্যয় হিসাব',
        sub: 'মাসিক আয়-ব্যয় বিশ্লেষণ, লাভ-লোকসান ও লেনদেনের লেজার',
        totalIncome: 'মোট আয়', totalExpense: 'মোট ব্যয়',
        netProfit: 'নিট মুনাফা', profitMargin: 'মুনাফার হার',
        vsLastMonth: 'গত মাসের তুলনায়',
        tabIncome: 'আয় বিশ্লেষণ', tabExpense: 'ব্যয় বিশ্লেষণ', tabLedger: 'লেজার',
        incomeTitle: 'আয়ের বিভাজন — জুন ২০২৬', incomeHint: 'চলতি মাস · সব রাজস্বের উৎস',
        expenseTitle: 'ব্যয়ের বিভাজন — জুন ২০২৬', expenseHint: 'চলতি মাস · মাসিক বাজেটের বিপরীতে',
        ledgerTitle: 'লেনদেনের লেজার', ledgerHint: 'সাম্প্রতিক আয় ও ব্যয়ের এন্ট্রি — জুন ২০২৬',
        category: 'ক্যাটাগরি', amount: 'পরিমাণ', ofTotal: 'মোটের %',
        lastMonth: 'গত মাস', change: 'পরিবর্তন',
        budget: 'বাজেট', variance: 'পার্থক্য', underBudget: 'সাশ্রয়', overBudget: 'অতিরিক্ত',
        date: 'তারিখ', ref: 'রেফারেন্স', description: 'বিবরণ', type: 'ধরন',
        income: 'আয়', expense: 'ব্যয়', revenue: 'রাজস্ব',
        plTitle: 'মাসিক লাভ-লোকসান — শেষ ৬ মাস', plHint: 'আয় ও ব্যয়ের তুলনামূলক চিত্র (৳ লাখ)',
        plMtdNote: 'জুন চলতি মাস (মাত্র প্রথম ১০ দিন)',
        tabRates: 'ভিলা ভাড়া', tabRestaurants: 'রেস্তোরাঁ',
        ratesTitle: 'ভিলা ভাড়া কার্ড ও অকুপেন্সি', ratesHint: '৬ ধরনের ভিলা · রাত্রিকালীন দাম · জুনের দখল হার',
        restTitle: 'রেস্তোরাঁর আয় ও মুনাফা', restHint: '৩ খাবারের জায়গা · খাদ্য খরচ বিশ্লেষণ · জুন চলতি মাস',
        villaType: 'ভিলার ধরন', nightRate: 'রাত্রিকালীন দাম', units: 'ইউনিট', occupancy: 'দখল হার',
        potentialRev: 'সম্ভাব্য রাজস্ব', actualRev: 'বাস্তব রাজস্ব',
        restaurant: 'রেস্তোরাঁ', cuisine: 'রান্নার ধরন', guests: 'অতিথি',
        foodCost: 'খাদ্য খরচ', avgBill: 'গড় বিল', margin: 'মুনাফা', marginPct: 'মুনাফা %',
        costPct: 'খাদ্য খরচ %', growth: 'মে থেকে বৃদ্ধি',
      },
      calendar: {
        title: 'বুকিং ক্যালেন্ডার', sub: 'মাসজুড়ে গ্রিড — প্রতিটি ভিলা, প্রতিটি রাত, এক নজরে',
        legendBooked: 'বুকড', legendFree: 'খালি', legendToday: 'আজ',
        clickHint: 'খালি ঘরে ক্লিক করলে নতুন বুকিং শুরু হবে · বারে হোভার করলে অতিথি ও তারিখ দেখাবে',
        room: 'ভিলা', months: ['জুন ২০২৬', 'জুলাই ২০২৬', 'আগস্ট ২০২৬'],
        occupancyOfMonth: 'মাসের অকুপেন্সি',
      },
      notif: {
        title: 'নোটিফিকেশন', markAll: 'সব পঠিত করুন', empty: 'সব দেখা হয়ে গেছে!',
        unread: 'নতুন',
      },
      cms: {
        title: 'সাইট কনটেন্ট (CMS)', sub: 'পাবলিক সাইটের প্রতিটি সেকশন নিয়ন্ত্রণ করুন — পরিবর্তন সাথে সাথে লাইভ হয়',
        liveNote: 'পরিবর্তন এই ব্রাউজারে স্বয়ংক্রিয়ভাবে সংরক্ষিত হয় এবং পাবলিক সাইটে সাথে সাথে দেখা যায়।',
        viewSite: 'পাবলিক সাইট খুলুন', reset: 'ডিফল্টে ফিরে যান',
        heroTitle: 'হোমপেজ হিরো', heroHint: 'শিরোনাম, উপশিরোনাম ও ব্যাকগ্রাউন্ড ছবি',
        imgUrl: 'ছবির URL', eyebrow: 'আইব্রো (শিরোনামের উপরের ছোট লাইন)',
        titlePart1: 'শিরোনাম — অংশ ১', titleEm: 'শিরোনাম — জোর দেওয়া শব্দ', titlePart2: 'শিরোনাম — অংশ ২',
        subText: 'উপশিরোনাম', enLbl: 'English', bnLbl: 'বাংলা',
        menuTitle: 'পাবলিক মেনু', menuHint: 'পাবলিক নেভিগেশনের আইটেম দেখান বা লুকান',
        navTitle: 'পাবলিক মেনু অ্যাক্সেস', navHint: 'পাবলিক নেভিগেশনের আইটেম চালুকরণ বা বন্ধকরণ',
        sectionsTitle: 'হোমপেজ সেকশন', sectionsHint: 'হোমপেজের পুরো সেকশন চালু/বন্ধ করুন',
        secTitle: 'হোমপেজ সেকশন টগলস', secHint: 'হোমপেজের যেকোনো সেকশন চালু বা বন্ধ করুন',
        sec: {
          stats: 'পরিসংখ্যান কাউন্টার', about: 'আমাদের কথা / গল্প', villas: 'ভিলা প্রিভিউ',
          experiences: 'অভিজ্ঞতা', custom: 'কাস্টম সেকশন', gallery: 'গ্যালারি মারকুই',
          testimonials: 'অতিথিদের গল্প', cta: 'বুকিং কল-টু-অ্যাকশন',
        },
        customTitle: 'কাস্টম শোকেস সেকশন', customHint: 'নিজের সেকশন যোগ করুন — ছবি, শিরোনাম ও বর্ণনা, দুই ভাষাতেই',
        addSection: 'সেকশন যোগ করুন', removeSection: 'মুছুন', visible: 'দৃশ্যমান',
        secTitle: 'সেকশনের শিরোনাম', secDesc: 'বর্ণনা',
        newSecTitleEn: 'New Section', newSecTitleBn: 'নতুন সেকশন',
        newSecDescEn: 'Write a short description here…', newSecDescBn: 'এখানে সংক্ষিপ্ত বর্ণনা লিখুন…',
      },
      print: {
        btn: 'প্রিন্ট / PDF', generated: 'তৈরি হয়েছে', doc: 'রিপোর্ট',
        brandLine: 'কুমিল্লা রিসোর্ট · কোটবাড়ি, কুমিল্লা, বাংলাদেশ',
      },
      reports: {
        title: 'রিপোর্ট', sub: 'পারফরম্যান্স ও আয়ের বিশ্লেষণ',
        revpar: 'RevPAR', adr: 'ADR', avgStay: 'গড় অবস্থান', rating: 'অতিথি রেটিং',
        yoy: 'বছরে', reviews: 'টি রিভিউ', stable: '২০২৫-এর মতোই', nightsUnit: 'রাত',
        monthlyTitle: 'মাসিক আয়', monthlyHint: 'শেষ ৬ মাস · সব আয়ের উৎস',
        channelTitle: 'চ্যানেল পারফরম্যান্স', channelHint: 'চ্যানেল অনুযায়ী বুকিং, জুন ২০২৬',
        export: 'এক্সপোর্ট', topExp: 'শীর্ষ অভিজ্ঞতা', topExpHint: 'এ মাসের বুকিং',
        directWeb: 'সরাসরি ওয়েবসাইট', agents: 'ট্রাভেল এজেন্ট', phone: 'পুনরায় / ফোন',
        summaryTitle: 'মাসিক সারসংক্ষেপ — জুন ২০২৬', summaryHint: 'পুরো কার্যক্রমের এক-পাতার চিত্র',
        occAvg: 'গড় অকুপেন্সি', revTotal: 'মোট আয় (চলতি মাস)', payrollTotal: 'বেতন খরচ',
        tasksDone: 'হাউসকিপিং সম্পন্ন কাজ', bookingsTotal: 'বুকিং (চলতি মাস)', otTotal: 'ওভারটাইম ঘণ্টা',
      },
      settings: {
        title: 'সেটিংস', sub: 'রিসোর্ট প্রোফাইল, ভাড়া ও পছন্দসমূহ',
        profile: 'রিসোর্ট প্রোফাইল', resortName: 'রিসোর্টের নাম', tagline: 'ট্যাগলাইন',
        taglineVal: 'যেখানে ইতিহাস ও পাহাড়ের মিলন ঘটে', addr: 'ঠিকানা',
        prefs: 'পছন্দসমূহ', defaultLang: 'ডিফল্ট ভাষা', currency: 'মুদ্রা',
        checkInTime: 'চেক-ইন সময়', checkOutTime: 'চেক-আউট সময়',
        rates: 'রাত্রিকালীন ভাড়া', notif: 'নোটিফিকেশন',
        notifList: ['নতুন বুকিংয়ে ইমেইল', 'বাতিলে এসএমএস', 'দৈনিক অকুপেন্সি সারাংশ', 'কম-মজুদ সতর্কতা'],
        save: 'পরিবর্তন সংরক্ষণ', saved: 'সেটিংস সংরক্ষিত হয়েছে। (ডেমো)',
        english: 'English', bangla: 'বাংলা',
        tplTitle: 'এসএমএস / ইমেইল টেমপ্লেট', tplHint: 'নিশ্চিতকরণ বার্তা — {guest}, {villa}, {dates}, {ref}, {amount} স্বয়ংক্রিয়ভাবে বসে যায়',
        tplSave: 'টেমপ্লেট সংরক্ষণ করুন', tplSaved: 'টেমপ্লেট সংরক্ষিত হয়েছে। (ডেমো)',
      },
    },
  },
};
